package scanner

import (
	"context"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/muhananaufal/go-aether/internal/core/domain"
	"github.com/muhananaufal/go-aether/internal/core/port"
)

// GoCodeAuditor inspects a project against the practices a Go service needs to
// survive production.
//
// Every rule below encodes a failure that looks fine in development and only
// appears under load, after a deploy, or in an incident: precisely the class a
// newcomer cannot yet anticipate, and therefore the class worth naming.
type GoCodeAuditor struct {
	MaxDepth int
	MaxFiles int
}

var _ port.CodeAuditor = (*GoCodeAuditor)(nil)

// NewGoCodeAuditor constructs an auditor with the default bounds.
func NewGoCodeAuditor() *GoCodeAuditor {
	return &GoCodeAuditor{MaxDepth: DefaultMaxDepth, MaxFiles: DefaultMaxFiles}
}

// projectFacts accumulates evidence across the whole tree, because most of these
// rules are about something being absent, and absence can only be judged once
// every file has been seen.
type projectFacts struct {
	importsDatabaseSQL bool
	setsPoolLimits     bool

	declaresHTTPServer bool
	setsServerTimeouts bool

	mentionsHealth bool
	mentionsReady  bool

	hasTestFiles    bool
	hasLinterConfig bool
	hasEnvFile      bool
	gitignoreCovers bool

	unstructuredLogging []string
	panicsOutsideMain   []string
	backgroundContext   []string
	generatedTodos      []string
}

// Audit walks dir and produces a report.
func (a *GoCodeAuditor) Audit(ctx context.Context, dir string) (*domain.AuditReport, error) {
	maxDepth, maxFiles := a.MaxDepth, a.MaxFiles
	if maxDepth <= 0 {
		maxDepth = DefaultMaxDepth
	}
	if maxFiles <= 0 {
		maxFiles = DefaultMaxFiles
	}

	report := &domain.AuditReport{}
	facts := &projectFacts{}
	fset := token.NewFileSet()

	a.collectRootFiles(dir, facts)

	walkErr := filepath.WalkDir(dir, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			if entry != nil && entry.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if ctxErr := ctx.Err(); ctxErr != nil {
			return ctxErr
		}

		if entry.IsDir() {
			if path == dir {
				return nil
			}
			name := strings.ToLower(entry.Name())
			if _, skip := skippedDirNames[name]; skip || strings.HasPrefix(name, ".") {
				return filepath.SkipDir
			}
			if depthOf(dir, path) > maxDepth {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(entry.Name(), ".go") {
			return nil
		}
		if report.FilesSeen >= maxFiles {
			return filepath.SkipAll
		}
		report.FilesSeen++

		if strings.HasSuffix(entry.Name(), "_test.go") {
			facts.hasTestFiles = true
			return nil
		}

		src, readErr := os.ReadFile(path)
		if readErr != nil {
			return nil
		}
		a.inspectSource(string(src), relSlash(dir, path), facts, fset)
		return nil
	})

	if walkErr != nil && !isBenignWalkStop(walkErr) {
		return report, walkErr
	}

	a.evaluate(facts, report)
	return report, nil
}

// collectRootFiles checks the project-level files that are not Go source.
func (a *GoCodeAuditor) collectRootFiles(dir string, facts *projectFacts) {
	if _, err := os.Stat(filepath.Join(dir, ".env")); err == nil {
		facts.hasEnvFile = true
	}
	for _, name := range []string{".golangci.yml", ".golangci.yaml"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err == nil {
			facts.hasLinterConfig = true
		}
	}
	if raw, err := os.ReadFile(filepath.Join(dir, ".gitignore")); err == nil {
		for _, line := range strings.Split(string(raw), "\n") {
			if trimmed := strings.TrimSpace(line); trimmed == ".env" || trimmed == ".env*" {
				facts.gitignoreCovers = true
			}
		}
	}
}

func (a *GoCodeAuditor) inspectSource(src, relPath string, facts *projectFacts, fset *token.FileSet) {
	isMain := strings.HasPrefix(src, "package main") || strings.Contains(src, "\npackage main")
	isGenerated := strings.Contains(src, "Code generated by go-aether")

	if strings.Contains(src, `"database/sql"`) {
		facts.importsDatabaseSQL = true
	}
	if strings.Contains(src, "SetMaxOpenConns") || strings.Contains(src, "MaxConns =") {
		facts.setsPoolLimits = true
	}
	if strings.Contains(src, "&http.Server{") || strings.Contains(src, "http.Server{") {
		facts.declaresHTTPServer = true
	}
	if strings.Contains(src, "ReadTimeout") || strings.Contains(src, "ReadHeaderTimeout") {
		facts.setsServerTimeouts = true
	}
	if strings.Contains(src, "/health") {
		facts.mentionsHealth = true
	}
	if strings.Contains(src, "/ready") {
		facts.mentionsReady = true
	}

	if isGenerated && strings.Contains(src, "TODO") {
		facts.generatedTodos = append(facts.generatedTodos, relPath)
	}

	if isMain {
		// Everything below is about library code. panicking, logging without a
		// logger and constructing a root context are all reasonable in main.
		return
	}

	// The rules below inspect the syntax tree rather than the source text.
	//
	// Text matching flagged a comment that explained why not to panic, and a
	// string literal containing the word. An auditor that penalises a codebase
	// for documenting its own reasoning is one nobody will keep enabled.
	calls, hasContextParam, ok := analyseCalls(src, relPath, fset)
	if !ok {
		return
	}

	if calls.panics {
		facts.panicsOutsideMain = append(facts.panicsOutsideMain, relPath)
	}

	// Both remaining rules require a context to already be in scope. Without
	// that gate the auditor flags startup code for doing the right thing: a pool
	// constructor building its own context.Background() with a timeout, or a
	// config loader logging before any logger exists.
	if hasContextParam && calls.detachedContext {
		facts.backgroundContext = append(facts.backgroundContext, relPath)
	}
	if hasContextParam && calls.unstructuredLog {
		facts.unstructuredLogging = append(facts.unstructuredLogging, relPath)
	}
}

// callFacts records which constructs a file genuinely calls.
type callFacts struct {
	panics          bool
	detachedContext bool
	unstructuredLog bool
}

// analyseCalls parses the file and reports what it actually invokes.
//
// The boolean result is false when the file does not parse: a legacy repository
// may well contain such files, and guessing from text at that point would
// reintroduce exactly the false positives this function exists to remove.
func analyseCalls(src, relPath string, fset *token.FileSet) (callFacts, bool, bool) {
	var facts callFacts

	file, err := parser.ParseFile(fset, relPath, src, parser.SkipObjectResolution)
	if err != nil {
		return facts, false, false
	}

	hasContextParam := false

	ast.Inspect(file, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.FuncDecl:
			if funcTakesContext(node.Type) {
				hasContextParam = true
			}

		case *ast.FuncLit:
			if funcTakesContext(node.Type) {
				hasContextParam = true
			}

		case *ast.CallExpr:
			switch fn := node.Fun.(type) {
			case *ast.Ident:
				if fn.Name == "panic" {
					facts.panics = true
				}
			case *ast.SelectorExpr:
				pkg, isIdent := fn.X.(*ast.Ident)
				if !isIdent {
					return true
				}
				if pkg.Name == "context" && (fn.Sel.Name == "Background" || fn.Sel.Name == "TODO") {
					facts.detachedContext = true
				}
				if (pkg.Name == "fmt" || pkg.Name == "log") &&
					(fn.Sel.Name == "Println" || fn.Sel.Name == "Printf" || fn.Sel.Name == "Print") {
					facts.unstructuredLog = true
				}
			}
		}
		return true
	})

	return facts, hasContextParam, true
}

// funcTakesContext reports whether a signature accepts a context.Context, which
// is the most reliable available signal that the code sits on a request path.
func funcTakesContext(sig *ast.FuncType) bool {
	if sig == nil || sig.Params == nil {
		return false
	}
	for _, param := range sig.Params.List {
		sel, ok := param.Type.(*ast.SelectorExpr)
		if !ok {
			continue
		}
		pkg, ok := sel.X.(*ast.Ident)
		if ok && pkg.Name == "context" && sel.Sel.Name == "Context" {
			return true
		}
	}
	return false
}

// evaluate turns accumulated facts into findings.
func (a *GoCodeAuditor) evaluate(facts *projectFacts, report *domain.AuditReport) {
	if facts.hasEnvFile && !facts.gitignoreCovers {
		report.Add(domain.AuditFinding{
			Severity: domain.AuditCritical,
			Rule:     "secrets/env-not-ignored",
			Message:  ".env exists but .gitignore does not exclude it",
			Hint:     "Add '.env' to .gitignore now. A secret committed once stays in git history even after it is deleted.",
			File:     ".env",
		})
	}

	if facts.importsDatabaseSQL && !facts.setsPoolLimits {
		report.Add(domain.AuditFinding{
			Severity: domain.AuditWarn,
			Rule:     "db/unbounded-pool",
			Message:  "database/sql is used but no connection limit is set",
			Hint:     "Call SetMaxOpenConns, SetMaxIdleConns and SetConnMaxLifetime. The default is unlimited, so the ceiling is discovered when the database refuses connections under load.",
		})
	}

	if facts.declaresHTTPServer && !facts.setsServerTimeouts {
		report.Add(domain.AuditFinding{
			Severity: domain.AuditWarn,
			Rule:     "http/no-server-timeouts",
			Message:  "http.Server is constructed without timeouts",
			Hint:     "Set ReadTimeout, WriteTimeout and IdleTimeout. Without them one slow client holds a connection indefinitely, and enough of them exhaust the listener.",
		})
	}

	if facts.declaresHTTPServer && !facts.mentionsReady {
		report.Add(domain.AuditFinding{
			Severity: domain.AuditWarn,
			Rule:     "k8s/no-readiness-probe",
			Message:  "no readiness endpoint found",
			Hint:     "Run 'go-aether infra:healthcheck' to scaffold /livez and /readyz. Liveness says the process is alive; readiness says it can serve traffic, and without the distinction a rolling deploy sends requests to a pod still connecting to its database.",
		})
	}

	if facts.declaresHTTPServer && !facts.mentionsHealth {
		report.Add(domain.AuditFinding{
			Severity: domain.AuditWarn,
			Rule:     "k8s/no-liveness-probe",
			Message:  "no health endpoint found",
			Hint:     "Run 'go-aether infra:healthcheck'. Without a liveness endpoint the orchestrator cannot tell a wedged process from a healthy one, and leaves it in the load balancer.",
		})
	}

	if !facts.hasTestFiles {
		report.Add(domain.AuditFinding{
			Severity: domain.AuditWarn,
			Rule:     "test/no-tests",
			Message:  "the project contains no _test.go files",
			Hint:     "Start with the domain layer: it has no I/O, so its tests need no setup and run in microseconds.",
		})
	}

	if !facts.hasLinterConfig {
		report.Add(domain.AuditFinding{
			Severity: domain.AuditInfo,
			Rule:     "quality/no-linter-config",
			Message:  "no .golangci.yml found",
			Hint:     "Run 'go-aether infra:lint' to scaffold one.",
		})
	}

	addAll := func(files []string, severity domain.AuditSeverity, rule, message, hint string) {
		for _, file := range files {
			report.Add(domain.AuditFinding{
				Severity: severity, Rule: rule, Message: message, Hint: hint, File: file,
			})
		}
	}

	addAll(facts.panicsOutsideMain, domain.AuditWarn, "reliability/panic-in-library",
		"panic outside package main",
		"Return an error instead. A panic in a library package takes down every request in flight, not only the one that triggered it.")

	addAll(facts.backgroundContext, domain.AuditWarn, "context/detached-context",
		"context.Background or context.TODO in a request path",
		"Pass the request's context through. A detached context ignores cancellation, so a client that hangs up leaves the query running to completion.")

	addAll(facts.unstructuredLogging, domain.AuditWarn, "observability/unstructured-log",
		"fmt.Println or log.Println outside package main",
		"Use log/slog with the request context. Unstructured lines cannot be filtered by trace_id when an incident is in progress.")

	addAll(facts.generatedTodos, domain.AuditInfo, "scaffold/unfinished-todo",
		"generated file still contains a TODO",
		"These mark the implementation blocks go-aether deliberately left for you.")
}
