package domain

import (
	"fmt"
	"strings"
	"time"
)

// CurrentManifestVersion represents the supported specification schema version.
const CurrentManifestVersion = "1"

// AetherManifest is the Single Source of Truth (SSOT) representing a project's architecture identity.
type AetherManifest struct {
	Version      string           `yaml:"version" json:"version"`
	Project      ProjectInfo      `yaml:"project" json:"project"`
	Architecture ArchConfig       `yaml:"architecture" json:"architecture"`
	Stack        StackConfig      `yaml:"stack" json:"stack"`
	Adapters     AdapterConfig    `yaml:"adapters" json:"adapters"`
	Modules      []ModuleRegistry `yaml:"modules" json:"modules"`
	Workers      []WorkerRegistry `yaml:"workers" json:"workers"`
	Migrations   MigrationConfig  `yaml:"migrations" json:"migrations"`
	Lint         LintConfig       `yaml:"lint" json:"lint"`
	Test         TestConfig       `yaml:"test" json:"test"`
	Meta         MetaConfig       `yaml:"meta" json:"meta"`
}

// ProjectInfo stores essential Go module and tool metadata.
type ProjectInfo struct {
	Name          string `yaml:"name" json:"name"`
	Module        string `yaml:"module" json:"module"`
	GoVersion     string `yaml:"go_version" json:"go_version"`
	CreatedAt     string `yaml:"created_at" json:"created_at"`
	AetherVersion string `yaml:"aether_version" json:"aether_version"`
}

// ArchConfig dictates the structural pattern and layout paths of the repository.
type ArchConfig struct {
	Pattern string  `yaml:"pattern" json:"pattern"`
	Mode    string  `yaml:"mode" json:"mode"`
	Paths   PathMap `yaml:"paths" json:"paths"`
}

// PathMap holds the directory mapping for code layer generation.
type PathMap struct {
	Domain      string `yaml:"domain" json:"domain"`
	Port        string `yaml:"port" json:"port"`
	Service     string `yaml:"service" json:"service"`
	HandlerHTTP string `yaml:"handler_http" json:"handler_http"`
	HandlerGRPC string `yaml:"handler_grpc,omitempty" json:"handler_grpc,omitempty"`
	Repository  string `yaml:"repository" json:"repository"`
	Cmd         string `yaml:"cmd" json:"cmd"`
	Config      string `yaml:"config" json:"config"`
	Pkg         string `yaml:"pkg" json:"pkg"`
}

// StackConfig specifies the technological choices active across the application layers.
type StackConfig struct {
	Router    string   `yaml:"router" json:"router"`
	Database  DBConfig `yaml:"database" json:"database"`
	Cache     string   `yaml:"cache" json:"cache"`
	Transport []string `yaml:"transport" json:"transport"`
	Auth      string   `yaml:"auth" json:"auth"`
	Logger    string   `yaml:"logger" json:"logger"`
}

// DBConfig configures database driver and data access layer patterns.
type DBConfig struct {
	Driver string `yaml:"driver" json:"driver"`
	ORM    string `yaml:"orm" json:"orm"`
	Pool   string `yaml:"pool" json:"pool"`
}

// AdapterConfig holds existing variable symbols for brownfield BYO constructor injection.
type AdapterConfig struct {
	ExistingDBVar     string `yaml:"existing_db_var" json:"existing_db_var"`
	ExistingRedisVar  string `yaml:"existing_redis_var" json:"existing_redis_var"`
	ExistingLoggerVar string `yaml:"existing_logger_var" json:"existing_logger_var"`
}

// ModuleRegistry tracks features and modules generated by go-aether.
type ModuleRegistry struct {
	Name       string   `yaml:"name" json:"name"`
	CreatedAt  string   `yaml:"created_at" json:"created_at"`
	Transports []string `yaml:"transports" json:"transports"`
	HasCache   bool     `yaml:"has_cache" json:"has_cache"`
	HasWorker  bool     `yaml:"has_worker" json:"has_worker"`
}

// WorkerRegistry registers background processors in the system.
type WorkerRegistry struct {
	Name    string `yaml:"name" json:"name"`
	Broker  string `yaml:"broker" json:"broker"`
	Pattern string `yaml:"pattern" json:"pattern"`
}

// MigrationConfig specifies database migration execution engine.
type MigrationConfig struct {
	Tool string `yaml:"tool" json:"tool"`
	Dir  string `yaml:"dir" json:"dir"`
}

// LintConfig binds linter enforcement rules.
type LintConfig struct {
	Enabled bool   `yaml:"enabled" json:"enabled"`
	Config  string `yaml:"config" json:"config"`
}

// TestConfig sets quality gate rules including unit test coverage threshold.
type TestConfig struct {
	CoverageThreshold int `yaml:"coverage_threshold" json:"coverage_threshold"`
}

// MetaConfig preserves brownfield operational metadata and legacy notes.
type MetaConfig struct {
	AnomalyMode bool   `yaml:"anomaly_mode" json:"anomaly_mode"`
	LegacyNotes string `yaml:"legacy_notes" json:"legacy_notes"`
}

// NewDefaultManifest constructs an idiomatic greenfield manifest for a newly initialized project.
func NewDefaultManifest(name, module, goVersion, arch, dbDriver, router string) *AetherManifest {
	if arch == "" {
		arch = "hexagonal"
	}
	if router == "" {
		router = "chi"
	}
	if dbDriver == "" {
		dbDriver = "postgres"
	}

	now := time.Now().Format(time.RFC3339)
	return &AetherManifest{
		Version: CurrentManifestVersion,
		Project: ProjectInfo{
			Name:          name,
			Module:        module,
			GoVersion:     goVersion,
			CreatedAt:     now,
			AetherVersion: "0.1.0",
		},
		Architecture: ArchConfig{
			Pattern: arch,
			Mode:    "greenfield",
			Paths: PathMap{
				Domain:      "internal/core/domain",
				Port:        "internal/core/port",
				Service:     "internal/core/service",
				HandlerHTTP: "internal/adapter/handler/http",
				Repository:  "internal/adapter/repository",
				Cmd:         "cmd/server",
				Config:      "internal/config",
				Pkg:         "pkg",
			},
		},
		Stack: StackConfig{
			Router: router,
			Database: DBConfig{
				Driver: dbDriver,
				ORM:    "sqlc",
				Pool:   "pgxpool",
			},
			Cache:     "none",
			Transport: []string{"http"},
			Auth:      "none",
			Logger:    "slog-otel",
		},
		Adapters: AdapterConfig{},
		Modules:  []ModuleRegistry{},
		Workers:  []WorkerRegistry{},
		Migrations: MigrationConfig{
			Tool: "goose",
			Dir:  "migrations/",
		},
		Lint: LintConfig{
			Enabled: true,
			Config:  ".golangci.yml",
		},
		Test: TestConfig{
			CoverageThreshold: 80,
		},
		Meta: MetaConfig{
			AnomalyMode: false,
			LegacyNotes: "",
		},
	}
}

// Validate verifies the structural logic and required constraints of the manifest.
func (m *AetherManifest) Validate() error {
	if m.Version != CurrentManifestVersion {
		return fmt.Errorf("%w: expected v%s, got v%s", ErrManifestUnsupported, CurrentManifestVersion, m.Version)
	}
	if strings.TrimSpace(m.Project.Name) == "" || strings.TrimSpace(m.Project.Module) == "" {
		return fmt.Errorf("%w: project name and go module cannot be empty", ErrManifestCorrupt)
	}
	if m.Architecture.Pattern == "" {
		return fmt.Errorf("%w: architecture pattern must be explicitly declared", ErrManifestCorrupt)
	}
	// Check for duplicate modules
	seen := make(map[string]struct{})
	for _, mod := range m.Modules {
		if _, exists := seen[mod.Name]; exists {
			return fmt.Errorf("%w: %s", ErrModuleAlreadyExists, mod.Name)
		}
		seen[mod.Name] = struct{}{}
	}
	return nil
}

// HasModule checks if a feature module is already registered in the manifest.
func (m *AetherManifest) HasModule(name string) bool {
	for _, mod := range m.Modules {
		if strings.EqualFold(mod.Name, name) {
			return true
		}
	}
	return false
}

// AddModule registers a new module into the manifest safely.
func (m *AetherManifest) AddModule(reg ModuleRegistry) error {
	if m.HasModule(reg.Name) {
		return fmt.Errorf("%w: %s", ErrModuleAlreadyExists, reg.Name)
	}
	if reg.CreatedAt == "" {
		reg.CreatedAt = time.Now().Format(time.RFC3339)
	}
	m.Modules = append(m.Modules, reg)
	return nil
}
